### ISSUE TITLE
RSS Feed links are broken

### ISSUE THREAD

**Issue by porglezomp** [ticki/ticki.github.io#7]
The RSS feed links use relative URLs instead of absolute URLs (as they should) so I can't jump to the site from my RSS reader.

**Comment by ticki** [comment]
Could you open this in https://github.com/spf13/hugo instead?

**Comment by porglezomp** [comment]
I don't think it's a problem on the hugo side, since I follow a few other hugo blogs with working links, it's probably in one of your config files.

The `<link>` on line 5 of `index.xml` is a relative link pointing to `/` when it should point to `https://ticki.github.io/` instead. Presumably you need to set your root url somewhere before compiling.

**Comment by porglezomp** [comment]
I think you need to set `baseurl` in your `config.toml` to an absolute URL in order for the RSS feed to correctly use absolute links.

**Comment by ticki** [comment]
I believe it is fixed now.

**Comment by porglezomp** [comment]
Thanks, it works perfectly in my feed reader now!
